spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=telioarts;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create

# Forcer l'utilisation du schéma 'dbo' pour éviter que Hibernate ne cherche
# les tables dans le mauvais chemin par défaut
spring.jpa.properties.hibernate.default_schema=dbo

# Utiliser le mode 'validate' : Hibernate vérifie strictement que
# la structure des entités correspond aux tables existantes en base de données, sans rien modifier
spring.jpa.hibernate.ddl-auto=update

#Détail des requêtes pour le développement //ajout de log pour tracer les requêtes SQL générées,
# traces d'appel Spring pour JDBC (rappel cours)
logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.springframework.security=DEBUG

#Message bundles encoding
spring.messages.encoding=UTF-8
